# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class PrintStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Feed = channel.unary_unary(
            '/Print/Feed',
            request_serializer=service__pb2.Contents.SerializeToString,
            response_deserializer=service__pb2.Data.FromString,
        )


class PrintServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Feed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrintServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Feed': grpc.unary_unary_rpc_method_handler(
            servicer.Feed,
            request_deserializer=service__pb2.Contents.FromString,
            response_serializer=service__pb2.Data.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Print', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Print(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Feed(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Print/Feed',
                                             service__pb2.Contents.SerializeToString,
                                             service__pb2.Data.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
