# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"\x18\n\x08\x43ontents\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x66\x65\x65\x64\x18\x01 \x01(\t2#\n\x05Print\x12\x1a\n\x04\x46\x65\x65\x64\x12\t.Contents\x1a\x05.Data\"\x00\x62\x06proto3'
)




_CONTENTS = _descriptor.Descriptor(
  name='Contents',
  full_name='Contents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Contents.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=41,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feed', full_name='Data.feed', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['Contents'] = _CONTENTS
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Contents = _reflection.GeneratedProtocolMessageType('Contents', (_message.Message,), {
  'DESCRIPTOR' : _CONTENTS,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Contents)
  })
_sym_db.RegisterMessage(Contents)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)



_PRINT = _descriptor.ServiceDescriptor(
  name='Print',
  full_name='Print',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=65,
  serialized_end=100,
  methods=[
  _descriptor.MethodDescriptor(
    name='Feed',
    full_name='Print.Feed',
    index=0,
    containing_service=None,
    input_type=_CONTENTS,
    output_type=_DATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRINT)

DESCRIPTOR.services_by_name['Print'] = _PRINT

# @@protoc_insertion_point(module_scope)
